<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Tatar7" failures="11" tests="21" name="Command line test" time="159.996" errors="0" timestamp="29 May 2019 02:26:15 GMT">
  <testcase classname="io.platform.project.tests.CatalogPageTest" name="testGoToLoginPage" time="2.239"/>
  <testcase classname="io.platform.project.tests.CatalogPageTest" name="testLoggedIn" time="0.239"/>
  <testcase classname="io.platform.project.tests.CatalogPageTest" name="testPageHeader" time="0.077">
    <failure type="java.lang.AssertionError" message="expected [Welcome to iBusiness] but found [My Account Information]">
      <![CDATA[java.lang.AssertionError: expected [Welcome to iBusiness] but found [My Account Information]
	at io.platform.project.tests.CatalogPageTest.testPageHeader(CatalogPageTest.java:31)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- testPageHeader -->
  <testcase classname="io.platform.project.tests.ContactUsTest" name="contactUsTest" time="0.084">
    <failure type="java.lang.RuntimeException" message="Malformed email address">
      <![CDATA[java.lang.RuntimeException: Malformed email address
	at io.platform.project.pageObjects.ContactUsPage.fillInEmailTextBox(ContactUsPage.java:58)
	at io.platform.project.tests.ContactUsTest.contactUsTest(ContactUsTest.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- contactUsTest -->
  <testcase classname="io.platform.project.tests.ContactUsTest" name="contactUsTest" time="0.557">
    <failure type="java.lang.AssertionError" message="expected [Your enquiry has been successfully sent to the Store Owner.] but found [Full Name:
E-Mail Address:
Enquiry: Howdy!]">
      <![CDATA[java.lang.AssertionError: expected [Your enquiry has been successfully sent to the Store Owner.] but found [Full Name:
E-Mail Address:
Enquiry: Howdy!]
	at io.platform.project.tests.ContactUsTest.contactUsTest(ContactUsTest.java:39)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- contactUsTest -->
  <testcase classname="io.platform.project.tests.ContactUsTest" name="contactUsTest" time="0.11">
    <failure type="java.lang.RuntimeException" message="Malformed email address">
      <![CDATA[java.lang.RuntimeException: Malformed email address
	at io.platform.project.pageObjects.ContactUsPage.fillInEmailTextBox(ContactUsPage.java:58)
	at io.platform.project.tests.ContactUsTest.contactUsTest(ContactUsTest.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- contactUsTest -->
  <testcase classname="io.platform.project.tests.ContactUsTest" name="contactUsTest" time="0.117">
    <failure type="java.lang.RuntimeException" message="Malformed email address">
      <![CDATA[java.lang.RuntimeException: Malformed email address
	at io.platform.project.pageObjects.ContactUsPage.fillInEmailTextBox(ContactUsPage.java:58)
	at io.platform.project.tests.ContactUsTest.contactUsTest(ContactUsTest.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- contactUsTest -->
  <testcase classname="io.platform.project.tests.ContactUsTest" name="contactUsTest" time="0.113">
    <failure type="java.lang.RuntimeException" message="Malformed email address">
      <![CDATA[java.lang.RuntimeException: Malformed email address
	at io.platform.project.pageObjects.ContactUsPage.fillInEmailTextBox(ContactUsPage.java:58)
	at io.platform.project.tests.ContactUsTest.contactUsTest(ContactUsTest.java:36)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- contactUsTest -->
  <testcase classname="io.platform.project.tests.ContactUsTest" name="contactUsTest" time="0.597">
    <failure type="java.lang.AssertionError" message="expected [Your enquiry has been successfully sent to the Store Owner.] but found [Full Name:
E-Mail Address:
Enquiry: Howdy!]">
      <![CDATA[java.lang.AssertionError: expected [Your enquiry has been successfully sent to the Store Owner.] but found [Full Name:
E-Mail Address:
Enquiry: Howdy!]
	at io.platform.project.tests.ContactUsTest.contactUsTest(ContactUsTest.java:39)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- contactUsTest -->
  <testcase classname="io.platform.project.tests.CreateNewAccountTest" name="test" time="7.632">
    <failure type="java.lang.AssertionError" message="expected [Your Account Has Been Created!] but found [My Account Information]">
      <![CDATA[java.lang.AssertionError: expected [Your Account Has Been Created!] but found [My Account Information]
	at io.platform.project.tests.CreateNewAccountTest.test(CreateNewAccountTest.java:57)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase classname="io.platform.project.tests.FailureTest" name="testLogOff" time="4.101">
    <failure type="java.lang.RuntimeException" message="Element cannot be found">
      <![CDATA[java.lang.RuntimeException: Element cannot be found
	at io.platform.project.commons.Common.clickElement(Common.java:57)
	at io.platform.project.pageObjects.CatalogPage.clickLogOffButton(CatalogPage.java:132)
	at io.platform.project.tests.FailureTest.testLogOff(FailureTest.java:32)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testLogOff -->
  <testcase classname="io.platform.project.tests.ForgotPasswordTest" name="testForgotPasswordBackButton" time="4.821"/>
  <testcase classname="io.platform.project.tests.ForgotPasswordTest" name="testForgotPasswordBadEmailAddress" time="4.694"/>
  <testcase classname="io.platform.project.tests.ForgotPasswordTest" name="testForgotPasswordGoodEmailAddress" time="7.109"/>
  <testcase classname="io.platform.project.tests.ForgotPasswordTest" name="testForgotPasswordGoodEmailAddressSecondRequest" time="5.082"/>
  <testcase classname="io.platform.project.tests.ForgotPasswordTest" name="testForgotPasswordNoEmailAddress" time="4.766"/>
  <testcase classname="io.platform.project.tests.LoginTest" name="testLogin" time="5.098"/>
  <testcase classname="io.platform.project.tests.LoginTest" name="testLogin" time="2.619">
    <failure type="java.lang.AssertionError" message="expected [Welcome to iBusiness] but found [Welcome, Please Sign In]">
      <![CDATA[java.lang.AssertionError: expected [Welcome to iBusiness] but found [Welcome, Please Sign In]
	at io.platform.project.tests.LoginTest.testLogin(LoginTest.java:41)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- testLogin -->
  <testcase classname="io.platform.project.tests.LoginTest" name="testLogin" time="2.772">
    <failure type="java.lang.AssertionError" message="expected [Welcome to iBusiness] but found [Welcome, Please Sign In]">
      <![CDATA[java.lang.AssertionError: expected [Welcome to iBusiness] but found [Welcome, Please Sign In]
	at io.platform.project.tests.LoginTest.testLogin(LoginTest.java:41)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- testLogin -->
  <testcase classname="io.platform.project.tests.PlaceAndConfirmOrderTest" name="test" time="14.956"/>
  <testcase classname="io.platform.project.tests.PrintSearchResultsTest" name="printAllResultTitles" time="7.675"/>
</testsuite> <!-- Command line test -->
