<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="21" passed="11" failed="10" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-05-29T01:59:25Z" name="Command line suite" finished-at="2019-05-29T02:02:12Z" duration-ms="167137">
    <groups>
    </groups>
    <test started-at="2019-05-29T01:59:25Z" name="Command line test" finished-at="2019-05-29T02:02:12Z" duration-ms="167137">
      <class name="io.platform.project.tests.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.LoginTest@4e718207]" started-at="2019-05-28T19:01:14Z" name="setUp" finished-at="2019-05-28T19:01:18Z" duration-ms="3941" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testLogin(java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.LoginTest@4e718207]" started-at="2019-05-28T19:01:18Z" name="testLogin" data-provider="credentials" finished-at="2019-05-28T19:01:23Z" duration-ms="4843" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[lars@test.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.LoginTest@4e718207]" started-at="2019-05-28T19:01:23Z" name="tearDown" finished-at="2019-05-28T19:01:23Z" duration-ms="55" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLogin status=SUCCESS method=LoginTest.testLogin(java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.LoginTest@4e718207] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.LoginTest@4e718207]" started-at="2019-05-28T19:01:23Z" name="setUp" finished-at="2019-05-28T19:01:27Z" duration-ms="3935" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testLogin(java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.LoginTest@4e718207]" started-at="2019-05-28T19:01:27Z" name="testLogin" data-provider="credentials" finished-at="2019-05-28T19:01:30Z" duration-ms="2695" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome to iBusiness] but found [Welcome, Please Sign In]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome to iBusiness] but found [Welcome, Please Sign In]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at io.platform.project.tests.LoginTest.testLogin(LoginTest.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.LoginTest@4e718207]" started-at="2019-05-28T19:01:30Z" name="tearDown" finished-at="2019-05-28T19:01:30Z" duration-ms="380" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLogin status=FAILURE method=LoginTest.testLogin(java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.LoginTest@4e718207] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.LoginTest@4e718207]" started-at="2019-05-28T19:01:30Z" name="setUp" finished-at="2019-05-28T19:01:34Z" duration-ms="4105" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testLogin(java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.LoginTest@4e718207]" started-at="2019-05-28T19:01:34Z" name="testLogin" data-provider="credentials" finished-at="2019-05-28T19:01:37Z" duration-ms="2819" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[lars@test.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[incorrect]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome to iBusiness] but found [Welcome, Please Sign In]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome to iBusiness] but found [Welcome, Please Sign In]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at io.platform.project.tests.LoginTest.testLogin(LoginTest.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.LoginTest@4e718207]" started-at="2019-05-28T19:01:37Z" name="tearDown" finished-at="2019-05-28T19:01:37Z" duration-ms="357" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLogin status=FAILURE method=LoginTest.testLogin(java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.LoginTest@4e718207] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- io.platform.project.tests.LoginTest -->
      <class name="io.platform.project.tests.CatalogPageTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:io.platform.project.tests.CatalogPageTest@1d371b2d]" started-at="2019-05-28T18:59:25Z" name="setup" finished-at="2019-05-28T18:59:29Z" duration-ms="4854" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testGoToLoginPage()[pri:0, instance:io.platform.project.tests.CatalogPageTest@1d371b2d]" started-at="2019-05-28T18:59:29Z" name="testGoToLoginPage" finished-at="2019-05-28T18:59:32Z" duration-ms="2549" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGoToLoginPage -->
        <test-method signature="testLoggedIn()[pri:0, instance:io.platform.project.tests.CatalogPageTest@1d371b2d]" started-at="2019-05-28T18:59:32Z" name="testLoggedIn" finished-at="2019-05-28T18:59:33Z" duration-ms="870" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoggedIn -->
        <test-method signature="testPageHeader()[pri:0, instance:io.platform.project.tests.CatalogPageTest@1d371b2d]" started-at="2019-05-28T18:59:33Z" name="testPageHeader" finished-at="2019-05-28T18:59:33Z" duration-ms="75" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome to iBusiness] but found [My Account Information]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome to iBusiness] but found [My Account Information]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at io.platform.project.tests.CatalogPageTest.testPageHeader(CatalogPageTest.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPageHeader -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:io.platform.project.tests.CatalogPageTest@1d371b2d]" started-at="2019-05-28T19:02:09Z" name="tearDown" finished-at="2019-05-28T19:02:12Z" duration-ms="3058" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- io.platform.project.tests.CatalogPageTest -->
      <class name="io.platform.project.tests.FailureTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:io.platform.project.tests.FailureTest@23fe1d71]" started-at="2019-05-28T19:00:19Z" name="setup" finished-at="2019-05-28T19:00:23Z" duration-ms="4016" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testLogOff()[pri:0, instance:io.platform.project.tests.FailureTest@23fe1d71]" started-at="2019-05-28T19:00:23Z" name="testLogOff" finished-at="2019-05-28T19:00:27Z" duration-ms="4089" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Element cannot be found]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Element cannot be found
	at io.platform.project.commons.Common.clickElement(Common.java:57)
	at io.platform.project.pageObjects.CatalogPage.clickLogOffButton(CatalogPage.java:132)
	at io.platform.project.tests.FailureTest.testLogOff(FailureTest.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogOff -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.FailureTest@23fe1d71]" started-at="2019-05-28T19:00:27Z" name="tearDown" finished-at="2019-05-28T19:00:28Z" duration-ms="398" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLogOff status=FAILURE method=FailureTest.testLogOff()[pri:0, instance:io.platform.project.tests.FailureTest@23fe1d71] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- io.platform.project.tests.FailureTest -->
      <class name="io.platform.project.tests.CreateNewAccountTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.CreateNewAccountTest@4d3167f4]" started-at="2019-05-28T19:00:07Z" name="setUp" finished-at="2019-05-28T19:00:11Z" duration-ms="3896" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="test()[pri:0, instance:io.platform.project.tests.CreateNewAccountTest@4d3167f4]" started-at="2019-05-28T19:00:11Z" name="test" finished-at="2019-05-28T19:00:19Z" duration-ms="7774" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Your Account Has Been Created!] but found [My Account Information]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Your Account Has Been Created!] but found [My Account Information]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at io.platform.project.tests.CreateNewAccountTest.test(CreateNewAccountTest.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:io.platform.project.tests.CreateNewAccountTest@4d3167f4]" started-at="2019-05-28T19:00:19Z" name="tearDown" finished-at="2019-05-28T19:00:19Z" duration-ms="50" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- io.platform.project.tests.CreateNewAccountTest -->
      <class name="io.platform.project.tests.ForgotPasswordTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:00:28Z" name="setUp" finished-at="2019-05-28T19:00:32Z" duration-ms="3833" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testForgotPasswordBackButton()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:00:32Z" name="testForgotPasswordBackButton" finished-at="2019-05-28T19:00:36Z" duration-ms="4855" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testForgotPasswordBackButton -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:00:36Z" name="tearDown" finished-at="2019-05-28T19:00:36Z" duration-ms="48" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testForgotPasswordBackButton status=SUCCESS method=ForgotPasswordTest.testForgotPasswordBackButton()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:00:36Z" name="setUp" finished-at="2019-05-28T19:00:40Z" duration-ms="3945" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testForgotPasswordBadEmailAddress()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:00:40Z" name="testForgotPasswordBadEmailAddress" finished-at="2019-05-28T19:00:45Z" duration-ms="4687" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testForgotPasswordBadEmailAddress -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:00:45Z" name="tearDown" finished-at="2019-05-28T19:00:45Z" duration-ms="50" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testForgotPasswordBadEmailAddress status=SUCCESS method=ForgotPasswordTest.testForgotPasswordBadEmailAddress()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:00:45Z" name="setUp" finished-at="2019-05-28T19:00:49Z" duration-ms="3932" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testForgotPasswordGoodEmailAddress()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:00:49Z" name="testForgotPasswordGoodEmailAddress" finished-at="2019-05-28T19:00:56Z" duration-ms="6944" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testForgotPasswordGoodEmailAddress -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:00:56Z" name="tearDown" finished-at="2019-05-28T19:00:56Z" duration-ms="47" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testForgotPasswordGoodEmailAddress status=SUCCESS method=ForgotPasswordTest.testForgotPasswordGoodEmailAddress()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:00:56Z" name="setUp" finished-at="2019-05-28T19:01:00Z" duration-ms="4001" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testForgotPasswordGoodEmailAddressSecondRequest()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:01:00Z" name="testForgotPasswordGoodEmailAddressSecondRequest" finished-at="2019-05-28T19:01:05Z" duration-ms="5082" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testForgotPasswordGoodEmailAddressSecondRequest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:01:05Z" name="tearDown" finished-at="2019-05-28T19:01:05Z" duration-ms="46" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testForgotPasswordGoodEmailAddressSecondRequest status=SUCCESS method=ForgotPasswordTest.testForgotPasswordGoodEmailAddressSecondRequest()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:01:05Z" name="setUp" finished-at="2019-05-28T19:01:09Z" duration-ms="4196" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testForgotPasswordNoEmailAddress()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:01:09Z" name="testForgotPasswordNoEmailAddress" finished-at="2019-05-28T19:01:14Z" duration-ms="4755" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testForgotPasswordNoEmailAddress -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:01:14Z" name="tearDown" finished-at="2019-05-28T19:01:14Z" duration-ms="46" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testForgotPasswordNoEmailAddress status=SUCCESS method=ForgotPasswordTest.testForgotPasswordNoEmailAddress()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- io.platform.project.tests.ForgotPasswordTest -->
      <class name="io.platform.project.tests.PlaceAndConfirmOrderTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.PlaceAndConfirmOrderTest@13eb8acf]" started-at="2019-05-28T19:01:37Z" name="setUp" finished-at="2019-05-28T19:01:41Z" duration-ms="3983" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="test()[pri:0, instance:io.platform.project.tests.PlaceAndConfirmOrderTest@13eb8acf]" started-at="2019-05-28T19:01:41Z" name="test" finished-at="2019-05-28T19:01:57Z" duration-ms="15540" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.PlaceAndConfirmOrderTest@13eb8acf]" started-at="2019-05-28T19:01:57Z" name="tearDown" finished-at="2019-05-28T19:01:57Z" duration-ms="51" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test status=SUCCESS method=PlaceAndConfirmOrderTest.test()[pri:0, instance:io.platform.project.tests.PlaceAndConfirmOrderTest@13eb8acf] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- io.platform.project.tests.PlaceAndConfirmOrderTest -->
      <class name="io.platform.project.tests.PrintSearchResultsTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.PrintSearchResultsTest@28ac3dc3]" started-at="2019-05-28T19:01:57Z" name="setUp" finished-at="2019-05-28T19:02:01Z" duration-ms="4035" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="printAllResultTitles()[pri:0, instance:io.platform.project.tests.PrintSearchResultsTest@28ac3dc3]" started-at="2019-05-28T19:02:01Z" name="printAllResultTitles" finished-at="2019-05-28T19:02:09Z" duration-ms="7703" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- printAllResultTitles -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.PrintSearchResultsTest@28ac3dc3]" started-at="2019-05-28T19:02:09Z" name="tearDown" finished-at="2019-05-28T19:02:09Z" duration-ms="49" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=printAllResultTitles status=SUCCESS method=PrintSearchResultsTest.printAllResultTitles()[pri:0, instance:io.platform.project.tests.PrintSearchResultsTest@28ac3dc3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- io.platform.project.tests.PrintSearchResultsTest -->
      <class name="io.platform.project.tests.ContactUsTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T18:59:33Z" name="setUp" finished-at="2019-05-28T18:59:39Z" duration-ms="6226" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T18:59:39Z" name="contactUsTest" data-provider="credentials" finished-at="2019-05-28T18:59:39Z" duration-ms="83" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Howdy!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Malformed email address]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Malformed email address
	at io.platform.project.pageObjects.ContactUsPage.fillInEmailTextBox(ContactUsPage.java:58)
	at io.platform.project.tests.ContactUsTest.contactUsTest(ContactUsTest.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactUsTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T18:59:39Z" name="tearDown" finished-at="2019-05-28T18:59:40Z" duration-ms="541" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=contactUsTest status=FAILURE method=ContactUsTest.contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T18:59:40Z" name="setUp" finished-at="2019-05-28T18:59:44Z" duration-ms="3897" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T18:59:44Z" name="contactUsTest" data-provider="credentials" finished-at="2019-05-28T18:59:49Z" duration-ms="5729" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[lars@test.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Howdy!]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactUsTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T18:59:49Z" name="tearDown" finished-at="2019-05-28T18:59:49Z" duration-ms="62" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=contactUsTest status=SUCCESS method=ContactUsTest.contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T18:59:49Z" name="setUp" finished-at="2019-05-28T18:59:53Z" duration-ms="3774" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T18:59:53Z" name="contactUsTest" data-provider="credentials" finished-at="2019-05-28T18:59:53Z" duration-ms="109" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Lars Jones]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Howdy!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Malformed email address]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Malformed email address
	at io.platform.project.pageObjects.ContactUsPage.fillInEmailTextBox(ContactUsPage.java:58)
	at io.platform.project.tests.ContactUsTest.contactUsTest(ContactUsTest.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactUsTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T18:59:53Z" name="tearDown" finished-at="2019-05-28T18:59:54Z" duration-ms="505" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=contactUsTest status=FAILURE method=ContactUsTest.contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T18:59:54Z" name="setUp" finished-at="2019-05-28T18:59:58Z" duration-ms="3826" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T18:59:58Z" name="contactUsTest" data-provider="credentials" finished-at="2019-05-28T18:59:58Z" duration-ms="116" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Lars Jones]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[lars@test]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Howdy!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Malformed email address]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Malformed email address
	at io.platform.project.pageObjects.ContactUsPage.fillInEmailTextBox(ContactUsPage.java:58)
	at io.platform.project.tests.ContactUsTest.contactUsTest(ContactUsTest.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactUsTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T18:59:58Z" name="tearDown" finished-at="2019-05-28T18:59:58Z" duration-ms="468" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=contactUsTest status=FAILURE method=ContactUsTest.contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T18:59:58Z" name="setUp" finished-at="2019-05-28T19:00:02Z" duration-ms="3844" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:00:02Z" name="contactUsTest" data-provider="credentials" finished-at="2019-05-28T19:00:02Z" duration-ms="124" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Lars Jones]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Howdy!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Malformed email address]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Malformed email address
	at io.platform.project.pageObjects.ContactUsPage.fillInEmailTextBox(ContactUsPage.java:58)
	at io.platform.project.tests.ContactUsTest.contactUsTest(ContactUsTest.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactUsTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:00:02Z" name="tearDown" finished-at="2019-05-28T19:00:03Z" duration-ms="462" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=contactUsTest status=FAILURE method=ContactUsTest.contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:00:03Z" name="setUp" finished-at="2019-05-28T19:00:07Z" duration-ms="3795" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:00:07Z" name="contactUsTest" data-provider="credentials" finished-at="2019-05-28T19:00:07Z" duration-ms="567" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Lars Jonse]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[lars@test.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Howdy!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Your enquiry has been successfully sent to the Store Owner.] but found [Full Name:
E-Mail Address:
Enquiry: Howdy!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Your enquiry has been successfully sent to the Store Owner.] but found [Full Name:
E-Mail Address:
Enquiry: Howdy!]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at io.platform.project.tests.ContactUsTest.contactUsTest(ContactUsTest.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactUsTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:00:07Z" name="tearDown" finished-at="2019-05-28T19:00:07Z" duration-ms="401" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=contactUsTest status=FAILURE method=ContactUsTest.contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- io.platform.project.tests.ContactUsTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
