<?xml version="1.0" encoding="UTF-8"?>
<testng-results total="21" passed="10" failed="11" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-05-29T02:23:35Z" name="Command line suite" finished-at="2019-05-29T02:26:15Z" duration-ms="159996">
    <groups>
    </groups>
    <test started-at="2019-05-29T02:23:35Z" name="Command line test" finished-at="2019-05-29T02:26:15Z" duration-ms="159996">
      <class name="io.platform.project.tests.LoginTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.LoginTest@4e718207]" started-at="2019-05-28T19:25:18Z" name="setUp" finished-at="2019-05-28T19:25:22Z" duration-ms="4073" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testLogin(java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.LoginTest@4e718207]" started-at="2019-05-28T19:25:22Z" name="testLogin" data-provider="credentials" finished-at="2019-05-28T19:25:27Z" duration-ms="5098" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[lars@test.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.LoginTest@4e718207]" started-at="2019-05-28T19:25:27Z" name="tearDown" finished-at="2019-05-28T19:25:27Z" duration-ms="48" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLogin status=SUCCESS method=LoginTest.testLogin(java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.LoginTest@4e718207] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.LoginTest@4e718207]" started-at="2019-05-28T19:25:27Z" name="setUp" finished-at="2019-05-28T19:25:31Z" duration-ms="4163" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testLogin(java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.LoginTest@4e718207]" started-at="2019-05-28T19:25:31Z" name="testLogin" data-provider="credentials" finished-at="2019-05-28T19:25:34Z" duration-ms="2619" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome to iBusiness] but found [Welcome, Please Sign In]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome to iBusiness] but found [Welcome, Please Sign In]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at io.platform.project.tests.LoginTest.testLogin(LoginTest.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.LoginTest@4e718207]" started-at="2019-05-28T19:25:34Z" name="tearDown" finished-at="2019-05-28T19:25:34Z" duration-ms="348" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLogin status=FAILURE method=LoginTest.testLogin(java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.LoginTest@4e718207] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.LoginTest@4e718207]" started-at="2019-05-28T19:25:34Z" name="setUp" finished-at="2019-05-28T19:25:38Z" duration-ms="4019" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testLogin(java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.LoginTest@4e718207]" started-at="2019-05-28T19:25:38Z" name="testLogin" data-provider="credentials" finished-at="2019-05-28T19:25:41Z" duration-ms="2772" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[lars@test.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[incorrect]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome to iBusiness] but found [Welcome, Please Sign In]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome to iBusiness] but found [Welcome, Please Sign In]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at io.platform.project.tests.LoginTest.testLogin(LoginTest.java:41)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.LoginTest@4e718207]" started-at="2019-05-28T19:25:41Z" name="tearDown" finished-at="2019-05-28T19:25:41Z" duration-ms="401" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLogin status=FAILURE method=LoginTest.testLogin(java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.LoginTest@4e718207] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- io.platform.project.tests.LoginTest -->
      <class name="io.platform.project.tests.CatalogPageTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:io.platform.project.tests.CatalogPageTest@1d371b2d]" started-at="2019-05-28T19:23:35Z" name="setup" finished-at="2019-05-28T19:23:39Z" duration-ms="4401" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testGoToLoginPage()[pri:0, instance:io.platform.project.tests.CatalogPageTest@1d371b2d]" started-at="2019-05-28T19:23:39Z" name="testGoToLoginPage" finished-at="2019-05-28T19:23:42Z" duration-ms="2239" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGoToLoginPage -->
        <test-method signature="testLoggedIn()[pri:0, instance:io.platform.project.tests.CatalogPageTest@1d371b2d]" started-at="2019-05-28T19:23:42Z" name="testLoggedIn" finished-at="2019-05-28T19:23:42Z" duration-ms="239" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLoggedIn -->
        <test-method signature="testPageHeader()[pri:0, instance:io.platform.project.tests.CatalogPageTest@1d371b2d]" started-at="2019-05-28T19:23:42Z" name="testPageHeader" finished-at="2019-05-28T19:23:42Z" duration-ms="77" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Welcome to iBusiness] but found [My Account Information]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Welcome to iBusiness] but found [My Account Information]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at io.platform.project.tests.CatalogPageTest.testPageHeader(CatalogPageTest.java:31)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testPageHeader -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:io.platform.project.tests.CatalogPageTest@1d371b2d]" started-at="2019-05-28T19:26:12Z" name="tearDown" finished-at="2019-05-28T19:26:15Z" duration-ms="3057" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- io.platform.project.tests.CatalogPageTest -->
      <class name="io.platform.project.tests.FailureTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:io.platform.project.tests.FailureTest@23fe1d71]" started-at="2019-05-28T19:24:21Z" name="setup" finished-at="2019-05-28T19:24:25Z" duration-ms="3993" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testLogOff()[pri:0, instance:io.platform.project.tests.FailureTest@23fe1d71]" started-at="2019-05-28T19:24:25Z" name="testLogOff" finished-at="2019-05-28T19:24:29Z" duration-ms="4101" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Element cannot be found]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Element cannot be found
	at io.platform.project.commons.Common.clickElement(Common.java:57)
	at io.platform.project.pageObjects.CatalogPage.clickLogOffButton(CatalogPage.java:132)
	at io.platform.project.tests.FailureTest.testLogOff(FailureTest.java:32)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogOff -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.FailureTest@23fe1d71]" started-at="2019-05-28T19:24:29Z" name="tearDown" finished-at="2019-05-28T19:24:30Z" duration-ms="393" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testLogOff status=FAILURE method=FailureTest.testLogOff()[pri:0, instance:io.platform.project.tests.FailureTest@23fe1d71] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- io.platform.project.tests.FailureTest -->
      <class name="io.platform.project.tests.ForgotPasswordTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:24:30Z" name="setUp" finished-at="2019-05-28T19:24:34Z" duration-ms="4184" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testForgotPasswordBackButton()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:24:34Z" name="testForgotPasswordBackButton" finished-at="2019-05-28T19:24:39Z" duration-ms="4821" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testForgotPasswordBackButton -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:24:39Z" name="tearDown" finished-at="2019-05-28T19:24:39Z" duration-ms="45" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testForgotPasswordBackButton status=SUCCESS method=ForgotPasswordTest.testForgotPasswordBackButton()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:24:39Z" name="setUp" finished-at="2019-05-28T19:24:43Z" duration-ms="3894" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testForgotPasswordBadEmailAddress()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:24:43Z" name="testForgotPasswordBadEmailAddress" finished-at="2019-05-28T19:24:48Z" duration-ms="4694" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testForgotPasswordBadEmailAddress -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:24:48Z" name="tearDown" finished-at="2019-05-28T19:24:48Z" duration-ms="47" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testForgotPasswordBadEmailAddress status=SUCCESS method=ForgotPasswordTest.testForgotPasswordBadEmailAddress()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:24:48Z" name="setUp" finished-at="2019-05-28T19:24:52Z" duration-ms="4110" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testForgotPasswordGoodEmailAddress()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:24:52Z" name="testForgotPasswordGoodEmailAddress" finished-at="2019-05-28T19:24:59Z" duration-ms="7109" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testForgotPasswordGoodEmailAddress -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:24:59Z" name="tearDown" finished-at="2019-05-28T19:24:59Z" duration-ms="47" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testForgotPasswordGoodEmailAddress status=SUCCESS method=ForgotPasswordTest.testForgotPasswordGoodEmailAddress()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:24:59Z" name="setUp" finished-at="2019-05-28T19:25:03Z" duration-ms="4348" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testForgotPasswordGoodEmailAddressSecondRequest()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:25:03Z" name="testForgotPasswordGoodEmailAddressSecondRequest" finished-at="2019-05-28T19:25:08Z" duration-ms="5082" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testForgotPasswordGoodEmailAddressSecondRequest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:25:08Z" name="tearDown" finished-at="2019-05-28T19:25:08Z" duration-ms="47" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testForgotPasswordGoodEmailAddressSecondRequest status=SUCCESS method=ForgotPasswordTest.testForgotPasswordGoodEmailAddressSecondRequest()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:25:08Z" name="setUp" finished-at="2019-05-28T19:25:13Z" duration-ms="4539" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testForgotPasswordNoEmailAddress()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:25:13Z" name="testForgotPasswordNoEmailAddress" finished-at="2019-05-28T19:25:18Z" duration-ms="4766" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testForgotPasswordNoEmailAddress -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d]" started-at="2019-05-28T19:25:18Z" name="tearDown" finished-at="2019-05-28T19:25:18Z" duration-ms="45" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testForgotPasswordNoEmailAddress status=SUCCESS method=ForgotPasswordTest.testForgotPasswordNoEmailAddress()[pri:0, instance:io.platform.project.tests.ForgotPasswordTest@543c6f6d] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- io.platform.project.tests.ForgotPasswordTest -->
      <class name="io.platform.project.tests.CreateNewAccountTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.CreateNewAccountTest@4d3167f4]" started-at="2019-05-28T19:24:10Z" name="setUp" finished-at="2019-05-28T19:24:14Z" duration-ms="3982" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="test()[pri:0, instance:io.platform.project.tests.CreateNewAccountTest@4d3167f4]" started-at="2019-05-28T19:24:14Z" name="test" finished-at="2019-05-28T19:24:21Z" duration-ms="7632" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Your Account Has Been Created!] but found [My Account Information]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Your Account Has Been Created!] but found [My Account Information]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at io.platform.project.tests.CreateNewAccountTest.test(CreateNewAccountTest.java:57)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:io.platform.project.tests.CreateNewAccountTest@4d3167f4]" started-at="2019-05-28T19:24:21Z" name="tearDown" finished-at="2019-05-28T19:24:21Z" duration-ms="57" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- io.platform.project.tests.CreateNewAccountTest -->
      <class name="io.platform.project.tests.PlaceAndConfirmOrderTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.PlaceAndConfirmOrderTest@13eb8acf]" started-at="2019-05-28T19:25:41Z" name="setUp" finished-at="2019-05-28T19:25:45Z" duration-ms="3997" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="test()[pri:0, instance:io.platform.project.tests.PlaceAndConfirmOrderTest@13eb8acf]" started-at="2019-05-28T19:25:45Z" name="test" finished-at="2019-05-28T19:26:00Z" duration-ms="14956" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.PlaceAndConfirmOrderTest@13eb8acf]" started-at="2019-05-28T19:26:00Z" name="tearDown" finished-at="2019-05-28T19:26:00Z" duration-ms="55" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test status=SUCCESS method=PlaceAndConfirmOrderTest.test()[pri:0, instance:io.platform.project.tests.PlaceAndConfirmOrderTest@13eb8acf] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- io.platform.project.tests.PlaceAndConfirmOrderTest -->
      <class name="io.platform.project.tests.PrintSearchResultsTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.PrintSearchResultsTest@28ac3dc3]" started-at="2019-05-28T19:26:00Z" name="setUp" finished-at="2019-05-28T19:26:04Z" duration-ms="3870" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="printAllResultTitles()[pri:0, instance:io.platform.project.tests.PrintSearchResultsTest@28ac3dc3]" started-at="2019-05-28T19:26:04Z" name="printAllResultTitles" finished-at="2019-05-28T19:26:12Z" duration-ms="7675" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- printAllResultTitles -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.PrintSearchResultsTest@28ac3dc3]" started-at="2019-05-28T19:26:12Z" name="tearDown" finished-at="2019-05-28T19:26:12Z" duration-ms="45" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=printAllResultTitles status=SUCCESS method=PrintSearchResultsTest.printAllResultTitles()[pri:0, instance:io.platform.project.tests.PrintSearchResultsTest@28ac3dc3] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- io.platform.project.tests.PrintSearchResultsTest -->
      <class name="io.platform.project.tests.ContactUsTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:23:42Z" name="setUp" finished-at="2019-05-28T19:23:46Z" duration-ms="3985" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:23:46Z" name="contactUsTest" data-provider="credentials" finished-at="2019-05-28T19:23:46Z" duration-ms="84" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Howdy!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Malformed email address]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Malformed email address
	at io.platform.project.pageObjects.ContactUsPage.fillInEmailTextBox(ContactUsPage.java:58)
	at io.platform.project.tests.ContactUsTest.contactUsTest(ContactUsTest.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactUsTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:23:46Z" name="tearDown" finished-at="2019-05-28T19:23:46Z" duration-ms="502" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=contactUsTest status=FAILURE method=ContactUsTest.contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:23:46Z" name="setUp" finished-at="2019-05-28T19:23:50Z" duration-ms="3876" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:23:50Z" name="contactUsTest" data-provider="credentials" finished-at="2019-05-28T19:23:51Z" duration-ms="557" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[lars@test.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Howdy!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Your enquiry has been successfully sent to the Store Owner.] but found [Full Name:
E-Mail Address:
Enquiry: Howdy!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Your enquiry has been successfully sent to the Store Owner.] but found [Full Name:
E-Mail Address:
Enquiry: Howdy!]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at io.platform.project.tests.ContactUsTest.contactUsTest(ContactUsTest.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactUsTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:23:51Z" name="tearDown" finished-at="2019-05-28T19:23:51Z" duration-ms="370" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=contactUsTest status=FAILURE method=ContactUsTest.contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:23:51Z" name="setUp" finished-at="2019-05-28T19:23:55Z" duration-ms="4084" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:23:55Z" name="contactUsTest" data-provider="credentials" finished-at="2019-05-28T19:23:55Z" duration-ms="110" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Lars Jones]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Howdy!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Malformed email address]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Malformed email address
	at io.platform.project.pageObjects.ContactUsPage.fillInEmailTextBox(ContactUsPage.java:58)
	at io.platform.project.tests.ContactUsTest.contactUsTest(ContactUsTest.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactUsTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:23:55Z" name="tearDown" finished-at="2019-05-28T19:23:56Z" duration-ms="499" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=contactUsTest status=FAILURE method=ContactUsTest.contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:23:56Z" name="setUp" finished-at="2019-05-28T19:24:00Z" duration-ms="3858" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:24:00Z" name="contactUsTest" data-provider="credentials" finished-at="2019-05-28T19:24:00Z" duration-ms="117" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Lars Jones]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[lars@test]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Howdy!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Malformed email address]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Malformed email address
	at io.platform.project.pageObjects.ContactUsPage.fillInEmailTextBox(ContactUsPage.java:58)
	at io.platform.project.tests.ContactUsTest.contactUsTest(ContactUsTest.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactUsTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:24:00Z" name="tearDown" finished-at="2019-05-28T19:24:00Z" duration-ms="461" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=contactUsTest status=FAILURE method=ContactUsTest.contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:24:00Z" name="setUp" finished-at="2019-05-28T19:24:04Z" duration-ms="3997" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:24:04Z" name="contactUsTest" data-provider="credentials" finished-at="2019-05-28T19:24:04Z" duration-ms="113" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Lars Jones]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[@gmail.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Howdy!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Malformed email address]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Malformed email address
	at io.platform.project.pageObjects.ContactUsPage.fillInEmailTextBox(ContactUsPage.java:58)
	at io.platform.project.tests.ContactUsTest.contactUsTest(ContactUsTest.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactUsTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:24:04Z" name="tearDown" finished-at="2019-05-28T19:24:05Z" duration-ms="522" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=contactUsTest status=FAILURE method=ContactUsTest.contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:24:05Z" name="setUp" finished-at="2019-05-28T19:24:09Z" duration-ms="3754" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:24:09Z" name="contactUsTest" data-provider="credentials" finished-at="2019-05-28T19:24:09Z" duration-ms="597" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Lars Jonse]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[lars@test.com]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Howdy!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Your enquiry has been successfully sent to the Store Owner.] but found [Full Name:
E-Mail Address:
Enquiry: Howdy!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Your enquiry has been successfully sent to the Store Owner.] but found [Full Name:
E-Mail Address:
Enquiry: Howdy!]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at org.testng.Assert.assertEquals(Assert.java:186)
	at io.platform.project.tests.ContactUsTest.contactUsTest(ContactUsTest.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:159)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- contactUsTest -->
        <test-method is-config="true" signature="tearDown(org.testng.ITestResult)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca]" started-at="2019-05-28T19:24:09Z" name="tearDown" finished-at="2019-05-28T19:24:10Z" duration-ms="401" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=contactUsTest status=FAILURE method=ContactUsTest.contactUsTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:io.platform.project.tests.ContactUsTest@32eebfca] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- io.platform.project.tests.ContactUsTest -->
    </test> <!-- Command line test -->
  </suite> <!-- Command line suite -->
</testng-results>
